#!/usr/bin/env python3
"""Build the Zendesk API tube-style map.

Generated by batch generator. 
"""

import sys
from pathlib import Path

sys.path.insert(0, "/Users/kinlane/GitHub/all/.claude/skills")
from _subway_engine import build_subway  # noqa: E402

ABBREV = {
    'Ticket Forms': 'Forms',
    'Ticket Fields': 'Fields',
    'User Fields': 'User Fields',
    'Org Fields': 'Org Fields',
    'Custom Objects': 'Custom Obj',
    'Custom Roles': 'Custom Roles',
    'Custom Status': 'Custom Status',
    'Object Layouts': 'Obj Layouts',
    'Audit Logs': 'Audit Logs',
}

LINES = [
    {
        "name": 'Tickets & Cases',
        "color": '#03363D',
        "stations": [
        ('Tickets', (270, 195)),
        ('Ticket Forms', (430, 175)),
        ('Ticket Fields', (610, 165)),
        ('Comments', (790, 175)),
        ('Attachments', (970, 200)),
        ],
    },
    {
        "name": 'Users & Orgs',
        "color": '#17494D',
        "stations": [
        ('Users', (270, 310)),
        ('User Fields', (430, 285)),
        ('Organizations', (610, 285)),
        ('Org Fields', (790, 285)),
        ('Groups', (960, 310)),
        ],
    },
    {
        "name": 'Content & Help Center',
        "color": '#7B3FE4',
        "stations": [
        ('Articles', (270, 425)),
        ('Categories', (440, 405)),
        ('Sections', (610, 405)),
        ('Topics', (790, 405)),
        ('Posts', (970, 425)),
        ],
    },
    {
        "name": 'Channels & Talk',
        "color": '#0E9D6E',
        "stations": [
        ('Channels', (270, 540)),
        ('Talk', (430, 515)),
        ('Chat', (590, 515)),
        ('Voice', (750, 515)),
        ('Email', (920, 540)),
        ],
    },
    {
        "name": 'Automation & Macros',
        "color": '#E68B1F',
        "stations": [
        ('Macros', (270, 660)),
        ('Triggers', (430, 635)),
        ('Automations', (590, 635)),
        ('Views', (750, 635)),
        ('SLAs', (920, 660)),
        ],
    },
    {
        "name": 'Custom Objects & Workflow',
        "color": '#1E5BD0',
        "stations": [
        ('Custom Objects', (290, 770)),
        ('Custom Roles', (490, 745)),
        ('Custom Status', (680, 745)),
        ('Object Layouts', (870, 770)),
        ],
    },
    {
        "name": 'Audit & Billing',
        "color": '#5A6275',
        "closed": True,
        "stations": [
        ('Account', (790, 815)),
        ('Brands', (905, 815)),
        ('Audit Logs', (790, 815)),
        ('OAuth', (675, 815)),
        ],
    },
]

URL_OVERRIDES = {
    'Tickets': 'https://apis.apis.io/apis/zendesk/tickets/',
    'Ticket Forms': 'https://apis.apis.io/apis/zendesk/ticket-forms/',
    'Ticket Fields': 'https://apis.apis.io/apis/zendesk/ticket-fields/',
    'Comments': 'https://apis.apis.io/apis/zendesk/comment-redactions/',
    'Attachments': 'https://apis.apis.io/apis/zendesk/attachments/',
    'Users': 'https://apis.apis.io/apis/zendesk/deleted-users/',
    'User Fields': 'https://apis.apis.io/apis/zendesk/user-fields/',
    'Organizations': 'https://apis.apis.io/apis/zendesk/organizations/',
    'Org Fields': 'https://apis.apis.io/apis/zendesk/organization-fields/',
    'Groups': 'https://apis.apis.io/apis/zendesk/groups/',
    'Articles': 'https://apis.apis.io/apis/zendesk/articles/',
    'Categories': 'https://apis.apis.io/apis/zendesk/categories/',
    'Sections': 'https://apis.apis.io/apis/zendesk/sections/',
    'Topics': 'https://apis.apis.io/apis/zendesk/topics/',
    'Posts': 'https://apis.apis.io/apis/zendesk/posts/',
    'Channels': 'https://apis.apis.io/apis/zendesk/channels/',
    'Talk': 'https://apis.apis.io/apis/zendesk/talk/',
    'Chat': 'https://apis.apis.io/apis/zendesk/chat-redactions/',
    'Voice': 'https://apis.apis.io/apis/zendesk/voice/',
    'Email': 'https://apis.apis.io/apis/zendesk/email-notifications/',
    'Macros': 'https://apis.apis.io/apis/zendesk/macros/',
    'Triggers': 'https://apis.apis.io/apis/zendesk/triggers/',
    'Automations': 'https://apis.apis.io/apis/zendesk/automations/',
    'Views': 'https://apis.apis.io/apis/zendesk/views/',
    'SLAs': 'https://apis.apis.io/apis/zendesk/group-slas/',
    'Custom Objects': 'https://apis.apis.io/apis/zendesk/custom-objects/',
    'Custom Roles': 'https://apis.apis.io/apis/zendesk/custom-roles/',
    'Custom Status': 'https://apis.apis.io/apis/zendesk/custom-statuses/',
    'Object Layouts': 'https://apis.apis.io/apis/zendesk/object-layouts/',
    'Account': 'https://apis.apis.io/apis/zendesk/account/',
    'Brands': 'https://apis.apis.io/apis/zendesk/brands/',
    'Audit Logs': 'https://apis.apis.io/apis/zendesk/audit-logs/',
    'OAuth': 'https://apis.apis.io/apis/zendesk/oauth/',
}


def main():
    seen = set()
    n_unique = 0
    for ln in LINES:
        for (st, _) in ln["stations"]:
            if st not in seen:
                n_unique += 1
                seen.add(st)
    build_subway(
        title='The Zendesk API · Underground Map',
        subtitle=f"{n_unique} APIs · {len(LINES)} functional lines · click any station for the apis.io page",
        lines=LINES,
        abbrev=ABBREV,
        source_label='Source: zendesk/openapi · github.com/api-evangelist/zendesk',
        out_dir=Path(__file__).resolve().parent,
        out_basename='zendesk-subway-map',
        provider_id='zendesk',
        station_url_overrides=URL_OVERRIDES,
    )


if __name__ == "__main__":
    main()
