openapi: 3.1.0
info:
  title: Activities
  description: Needs a description.
paths:
  /api/v2/activities:
    parameters:
      - $ref: '#/components/parameters/ActivitySince'
    get:
      operationId: ListActivities
      tags:
        - Activity Stream
      summary: Get  Api V2 Activities
      description: >
        Lists ticket activities in the last 30 days affecting the agent making
        the request.

        Also sideloads the following arrays of user records:


        - actors - All actors involved in the listed activities

        - users - All users involved in the listed activities


        #### Pagination


        - Cursor pagination (recommended)

        - Offset pagination


        See [Pagination](/api-reference/introduction/pagination/).


        Returns a maximum of 100 records per page.


        #### Allowed For


        * Agents
      responses:
        '200':
          description: Success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActivitiesResponse'
              examples:
                default:
                  $ref: '#/components/examples/ActivitiesResponseExample'
  /api/v2/activities/{activity_id}:
    parameters:
      - $ref: '#/components/parameters/ActivityId'
    get:
      operationId: ShowActivity
      tags:
        - Activity Stream
      summary: Get  Api V2 Activities Activity_id
      description: |
        Lists a specific activity.

        #### Allowed For

        * Agents
      responses:
        '200':
          description: Success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActivityResponse'
              examples:
                default:
                  $ref: '#/components/examples/ActivityResponseExample'
  /api/v2/activities/count:
    get:
      operationId: CountActivities
      tags:
        - Activity Stream
      summary: Get  Api V2 Activities Count
      description: >-
        Returns an approximate count of ticket activities in the last 30 days
        affecting the agent making the request. If the count exceeds 100,000,
        the count will return a cached result. This cached result will update
        every 24 hours.


        The `count[refreshed_at]` property is a timestamp that indicates when
        the count was last updated.


        **Note**: When the count exceeds 100,000, `count[refreshed_at]` may
        occasionally be null.

        This indicates that the count is being updated in the background, and
        `count[value]` is limited to 100,000 until the update is complete.


        #### Allowed For

        * Agents
      responses:
        '200':
          description: Count of ticket activities
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActivitiesCountResponse'
              examples:
                default:
                  $ref: '#/components/examples/ActivitiesCountResponseExample'
components:
  schemas:
    ActivitiesResponse:
      type: object
      properties:
        activities:
          type: array
          items:
            $ref: '#/components/schemas/ActivityObject'
          readOnly: true
        actors:
          type: array
          items:
            type: object
            additionalProperties: true
          readOnly: true
        count:
          type: integer
          readOnly: true
        next_page:
          type: string
          nullable: true
          readOnly: true
        previous_page:
          type: string
          nullable: true
          readOnly: true
        users:
          type: array
          items:
            type: object
            additionalProperties: true
          readOnly: true
      example:
        activities:
          - actor:
              active: true
              alias: ''
              created_at: '2020-11-17T00:32:12Z'
              custom_role_id: null
              default_group_id: 1873
              details: ''
              email: cgoddard+ted@zendesk.com
              external_id: null
              iana_time_zone: America/Juneau
              id: 158488612
              last_login_at: '2020-11-17T00:33:44Z'
              locale: en-gb
              locale_id: 5
              moderator: true
              name: Tedd
              notes: ''
              only_private_comments: false
              organization_id: null
              phone: null
              photo: null
              report_csv: true
              restricted_agent: false
              role: admin
              role_type: null
              shared: false
              shared_agent: false
              shared_phone_number: null
              signature: ''
              suspended: false
              tags: []
              ticket_restriction: null
              time_zone: Alaska
              two_factor_auth_enabled: null
              updated_at: '2020-11-17T00:34:38Z'
              url: https://example.zendesk.com/api/v2/users/158488612.json
              user_fields:
                its_remember_september: null
                skittles: null
                user_field_1: null
              verified: true
            actor_id: 158488612
            created_at: '2020-11-17T00:34:40Z'
            id: 29183462
            object:
              ticket:
                id: 1521
                subject: test
            target:
              ticket:
                id: 1521
                subject: test
            title: 'Tedd assigned ticket #1521 to you.'
            updated_at: '2020-11-17T00:34:40Z'
            url: https://example.zendesk.com/api/v2/activities/29183462.json
            user:
              active: true
              alias: test
              created_at: '2017-08-14T20:13:53Z'
              custom_role_id: null
              default_group_id: 1873
              details: ''
              email: user@zendesk.com
              external_id: oev7jj
              iana_time_zone: Pacific/Pago_Pago
              id: 3343
              last_login_at: '2020-11-16T22:57:45Z'
              locale: en-gb
              locale_id: 5
              moderator: true
              name: Samwise Gamgee
              notes: test
              only_private_comments: false
              organization_id: 1873
              phone: null
              photo:
                content_type: image/gif
                content_url: >-
                  https://example.zendesk.com/system/photos/8730791/1f84950b8d7949b3.gif
                deleted: false
                file_name: 1f84950b8d7949b3.gif
                height: 80
                id: 8730791
                inline: false
                mapped_content_url: >-
                  https://example.zendesk.com/system/photos/8730791/1f84950b8d7949b3.gif
                size: 4566
                thumbnails:
                  - content_type: image/gif
                    content_url: >-
                      https://example.zendesk.com/system/photos/8730801/1f84950b8d7949b3_thumb.gif
                    deleted: false
                    file_name: 1f84950b8d7949b3_thumb.gif
                    height: 32
                    id: 8730801
                    inline: false
                    mapped_content_url: >-
                      https://example.zendesk.com/system/photos/8730801/1f84950b8d7949b3_thumb.gif
                    size: 1517
                    url: >-
                      https://example.zendesk.com/api/v2/attachments/8730801.json
                    width: 32
                url: https://example.zendesk.com/api/v2/attachments/8730791.json
                width: 80
              report_csv: true
              restricted_agent: false
              role: admin
              role_type: null
              shared: false
              shared_agent: false
              shared_phone_number: null
              signature: test
              suspended: false
              tags:
                - '101'
              ticket_restriction: null
              time_zone: American Samoa
              two_factor_auth_enabled: null
              updated_at: '2020-11-17T00:33:55Z'
              url: https://example.zendesk.com/api/v2/users/3343.json
              user_fields:
                its_remember_september: null
                skittles: '2018-09-14T00:00:00+00:00'
                user_field_1: '101'
              verified: true
            user_id: 3343
            verb: tickets.assignment
        actors:
          - active: true
            alias: ''
            created_at: '2020-11-17T00:32:12Z'
            custom_role_id: null
            default_group_id: 1873
            details: ''
            email: cgoddard+ted@zendesk.com
            external_id: null
            iana_time_zone: America/Juneau
            id: 158488612
            last_login_at: '2020-11-17T00:33:44Z'
            locale: en-gb
            locale_id: 5
            moderator: true
            name: Tedd
            notes: ''
            only_private_comments: false
            organization_id: null
            phone: null
            photo: null
            report_csv: true
            restricted_agent: false
            role: admin
            role_type: null
            shared: false
            shared_agent: false
            shared_phone_number: null
            signature: ''
            suspended: false
            tags: []
            ticket_restriction: null
            time_zone: Alaska
            two_factor_auth_enabled: null
            updated_at: '2020-11-17T00:34:38Z'
            url: https://example.zendesk.com/api/v2/users/158488612.json
            user_fields:
              its_remember_september: null
              skittles: null
              user_field_1: null
            verified: true
        count: 1
        next_page: null
        previous_page: null
        users:
          - active: true
            alias: test
            created_at: '2017-08-14T20:13:53Z'
            custom_role_id: null
            default_group_id: 1873
            details: ''
            email: user@zendesk.com
            external_id: oev7jj
            iana_time_zone: Pacific/Pago_Pago
            id: 3343
            last_login_at: '2020-11-16T22:57:45Z'
            locale: en-gb
            locale_id: 5
            moderator: true
            name: Samwise Gamgee
            notes: test
            only_private_comments: false
            organization_id: 1873
            phone: null
            photo:
              content_type: image/gif
              content_url: >-
                https://example.zendesk.com/system/photos/8730791/1f84950b8d7949b3.gif
              deleted: false
              file_name: 1f84950b8d7949b3.gif
              height: 80
              id: 8730791
              inline: false
              mapped_content_url: >-
                https://example.zendesk.com/system/photos/8730791/1f84950b8d7949b3.gif
              size: 4566
              thumbnails:
                - content_type: image/gif
                  content_url: >-
                    https://example.zendesk.com/system/photos/8730801/1f84950b8d7949b3_thumb.gif
                  deleted: false
                  file_name: 1f84950b8d7949b3_thumb.gif
                  height: 32
                  id: 8730801
                  inline: false
                  mapped_content_url: >-
                    https://example.zendesk.com/system/photos/8730801/1f84950b8d7949b3_thumb.gif
                  size: 1517
                  url: https://example.zendesk.com/api/v2/attachments/8730801.json
                  width: 32
              url: https://example.zendesk.com/api/v2/attachments/8730791.json
              width: 80
            report_csv: true
            restricted_agent: false
            role: admin
            role_type: null
            shared: false
            shared_agent: false
            shared_phone_number: null
            signature: test
            suspended: false
            tags:
              - '101'
            ticket_restriction: null
            time_zone: American Samoa
            two_factor_auth_enabled: null
            updated_at: '2020-11-17T00:33:55Z'
            url: https://example.zendesk.com/api/v2/users/3343.json
            user_fields:
              its_remember_september: null
              skittles: '2018-09-14T00:00:00+00:00'
              user_field_1: '101'
            verified: true
    ActivityResponse:
      type: object
      properties:
        activity:
          $ref: '#/components/schemas/ActivityObject'
      example:
        activity:
          actor:
            active: true
            alias: ''
            created_at: '2020-11-17T00:32:12Z'
            custom_role_id: null
            default_group_id: 1873
            details: ''
            email: cgoddard+ted@zendesk.com
            external_id: null
            iana_time_zone: America/Juneau
            id: 158488612
            last_login_at: '2020-11-17T00:33:44Z'
            locale: en-gb
            locale_id: 5
            moderator: true
            name: Tedd
            notes: ''
            only_private_comments: false
            organization_id: null
            phone: null
            photo: null
            report_csv: true
            restricted_agent: false
            role: admin
            role_type: null
            shared: false
            shared_agent: false
            shared_phone_number: null
            signature: ''
            suspended: false
            tags: []
            ticket_restriction: null
            time_zone: Alaska
            two_factor_auth_enabled: null
            updated_at: '2020-11-17T00:34:38Z'
            url: https://example.zendesk.com/api/v2/users/158488612.json
            user_fields:
              its_remember_september: null
              skittles: null
              user_field_1: null
            verified: true
          actor_id: 158488612
          created_at: '2020-11-17T00:34:40Z'
          id: 29183462
          object:
            ticket:
              id: 1521
              subject: test
          target:
            ticket:
              id: 1521
              subject: test
          title: 'Tedd assigned ticket #1521 to you.'
          updated_at: '2020-11-17T00:34:40Z'
          url: https://example.zendesk.com/api/v2/activities/29183462.json
          user:
            active: true
            alias: test
            created_at: '2017-08-14T20:13:53Z'
            custom_role_id: null
            default_group_id: 1873
            details: ''
            email: user@zendesk.com
            external_id: oev7jj
            iana_time_zone: Pacific/Pago_Pago
            id: 3343
            last_login_at: '2020-11-16T22:57:45Z'
            locale: en-gb
            locale_id: 5
            moderator: true
            name: Samwise Gamgee
            notes: test
            only_private_comments: false
            organization_id: 1873
            phone: null
            photo:
              content_type: image/gif
              content_url: >-
                https://example.zendesk.com/system/photos/8730791/1f84950b8d7949b3.gif
              deleted: false
              file_name: 1f84950b8d7949b3.gif
              height: 80
              id: 8730791
              inline: false
              mapped_content_url: >-
                https://example.zendesk.com/system/photos/8730791/1f84950b8d7949b3.gif
              size: 4566
              thumbnails:
                - content_type: image/gif
                  content_url: >-
                    https://example.zendesk.com/system/photos/8730801/1f84950b8d7949b3_thumb.gif
                  deleted: false
                  file_name: 1f84950b8d7949b3_thumb.gif
                  height: 32
                  id: 8730801
                  inline: false
                  mapped_content_url: >-
                    https://example.zendesk.com/system/photos/8730801/1f84950b8d7949b3_thumb.gif
                  size: 1517
                  url: https://example.zendesk.com/api/v2/attachments/8730801.json
                  width: 32
              url: https://example.zendesk.com/api/v2/attachments/8730791.json
              width: 80
            report_csv: true
            restricted_agent: false
            role: admin
            role_type: null
            shared: false
            shared_agent: false
            shared_phone_number: null
            signature: test
            suspended: false
            tags:
              - '101'
            ticket_restriction: null
            time_zone: American Samoa
            two_factor_auth_enabled: null
            updated_at: '2020-11-17T00:33:55Z'
            url: https://example.zendesk.com/api/v2/users/3343.json
            user_fields:
              its_remember_september: null
              skittles: '2018-09-14T00:00:00+00:00'
              user_field_1: '101'
            verified: true
          user_id: 3343
          verb: tickets.assignment
    ActivitiesCountResponse:
      type: object
      properties:
        count:
          type: object
          properties:
            refreshed_at:
              type: string
              format: date-time
            value:
              type: integer
