openapi: 3.1.0
info:
  title: Skips
  description: Needs a description.
paths:
  /api/v2/skips:
    post:
      operationId: RecordNewSkip
      tags:
        - Ticket Skips
      summary: Post  Api V2 Skips
      description: |
        Record a new ticket skip for the current user.

        #### Allowed For

        * Agents
      responses:
        '201':
          description: Success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TicketSkipCreation'
              examples:
                default:
                  $ref: '#/components/examples/TicketSkipCreationExample'
  /api/v2/users/{user_id}/skips:
    parameters:
      - $ref: '#/components/parameters/SkipTicketUserId'
      - $ref: '#/components/parameters/TicketSortOrder'
      - $ref: '#/components/parameters/TicketId'
    get:
      operationId: ListTicketSkips
      tags:
        - Ticket Skips
      summary: Get  Api V2 Users User_id Skips
      description: >
        Archived tickets are not included in the response. See

        [About archived
        tickets](https://support.zendesk.com/hc/en-us/articles/203657756) in

        the Support Help Center.


        #### Pagination


        - Cursor pagination (recommended)

        - Offset pagination


        See [Pagination](/api-reference/introduction/pagination/).


        Returns a maximum of 100 records per page.


        #### Allowed For

        * Agents with "View only" or higher reports permissions in Support.
          These permissions are distinct from Explore permissions.
        * Agents retrieving their own skips
      responses:
        '200':
          description: Success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TicketSkipsResponse'
              examples:
                default:
                  $ref: '#/components/examples/TicketSkipResponseExample'
components:
  schemas:
    TicketSkipsResponse:
      type: object
      properties:
        skips:
          type: array
          items:
            $ref: '#/components/schemas/TicketSkipObject'
