openapi: 3.1.0
info:
  title: Ticket Audits
  description: Needs a description.
paths:
  /api/v2/ticket_audits:
    get:
      operationId: ListTicketAudits
      tags:
        - Ticket Audits
      summary: Get  Api V2 Ticket_audits
      description: >
        Returns ticket audits. Archived tickets are not included in the
        response. Use the [List Audits for a Ticket](#list-audits-for-a-ticket)
        endpoint to

        retrieve audit records for an archived ticket. To learn more about
        archived tickets, see [About archived
        tickets](https://support.zendesk.com/hc/en-us/articles/203657756).


        This endpoint should not be used for capturing change data. When
        continually chasing the tail of a cursor, some records will be skipped.
        For this use case, use the [Incremental Ticket Event Export
        API](/api-reference/ticketing/ticket-management/incremental_exports/#incremental-ticket-event-export).


        #### Allowed For


        * Admins
      parameters:
        - name: page[before]
          in: query
          description: >
            A [pagination
            cursor](/documentation/api-basics/pagination/paginating-through-lists-using-cursor-pagination)
            that tells the endpoint which page to start on. It should be a
            `meta.before_cursor` value from a previous request. Note:
            `page[before]` and `page[after]` can't be used together in the same
            request.
          schema:
            type: string
        - name: page[after]
          in: query
          description: >
            A [pagination
            cursor](/documentation/api-basics/pagination/paginating-through-lists-using-cursor-pagination)
            that tells the endpoint which page to start on. It should be a
            `meta.after_cursor` value from a previous request. Note:
            `page[before]` and `page[after]` can't be used together in the same
            request.
          schema:
            type: string
        - name: page[size]
          in: query
          description: >-
            Specifies how many records to be returned in the response. You can
            specify up to 100 records per page.
          schema:
            type: integer
      responses:
        '200':
          description: Success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TicketAuditsResponse'
              examples:
                default:
                  $ref: '#/components/examples/TicketAuditsResponseExample'
components:
  schemas:
    TicketAuditsResponse:
      type: object
      properties:
        after_cursor:
          type: string
          readOnly: true
        after_url:
          type: string
          readOnly: true
        audits:
          type: array
          items:
            $ref: '#/components/schemas/TicketAuditObject'
        before_cursor:
          type: string
          readOnly: true
        before_url:
          type: string
          readOnly: true
