openapi: 3.1.0
info:
  version: '1.0'
  title: Zendesk Account Account Settings User Passwords API
  description: Needs a description.
tags:
- name: User Passwords
paths:
  /api/v2/users/{user_id}/password:
    parameters:
    - $ref: '#/components/parameters/UserId'
    post:
      operationId: SetUserPassword
      tags:
      - User Passwords
      summary: Zendesk Post  Api V2 Users User_id Password
      description: 'An admin can set a user''s password only if the setting is enabled in Zendesk Support under **Settings** > **Security** > **Global**. The setting is off by default. Only the account owner can access and change this setting.


        #### Allowed For


        * Admins

        '
      responses:
        '200':
          description: Success description
          content:
            application/json:
              schema:
                type: string
                description: Empty response
                example: ''
              example: ''
    put:
      operationId: ChangeOwnPassword
      tags:
      - User Passwords
      summary: Zendesk Put  Api V2 Users User_id Password
      description: 'You can only change your own password. Nobody can change the password of another user because it requires knowing the user''s existing password. However, an admin can set a new password for another user without knowing the existing password. See [Set a User''s Password](#set-a-users-password) above.


        #### Allowed For


        * Agents

        * End Users

        '
      responses:
        '200':
          description: Success description
          content:
            application/json:
              schema:
                type: string
                description: Empty response
                example: ''
              example: ''
  /api/v2/users/{user_id}/password/requirements:
    parameters:
    - $ref: '#/components/parameters/UserId'
    get:
      operationId: GetUserPasswordRequirements
      tags:
      - User Passwords
      summary: Zendesk Get  Api V2 Users User_id Password Requirements
      description: '#### Allowed For


        * Agents

        * End Users

        '
      responses:
        '200':
          description: Success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserPasswordRequirementsResponse'
              examples:
                default:
                  $ref: '#/components/examples/UserPasswordRequirementsResponseExample'
components:
  schemas:
    UserPasswordRequirementsResponse:
      type: object
      properties:
        requirements:
          type: array
          items:
            type: string
