openapi: 3.1.0
info:
  version: '1.0'
  title: Zendesk Account Account Settings Custom Object Fields API
  description: Needs a description.
tags:
- name: Custom Object Fields
paths:
  /api/v2/custom_objects/{custom_object_key}/fields:
    get:
      operationId: ListCustomObjectFields
      tags:
      - Custom Object Fields
      summary: Zendesk Get  Api V2 Custom_objects Custom_object_key Fields
      description: 'Lists all undeleted custom fields for the specified object.


        #### Allowed For

        * Agents


        #### Pagination

        * Cursor pagination (recommended)

        * Offset pagination


        See [Pagination](/api-reference/introduction/pagination/).'
      parameters:
      - $ref: '#/components/parameters/CustomObjectKey'
      - $ref: '#/components/parameters/IncludeStandardFields'
      responses:
        '200':
          description: Success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomObjectFieldsResponse'
              examples:
                default:
                  $ref: '#/components/examples/CustomObjectFieldsResponseExample'
    post:
      operationId: CreateCustomObjectField
      tags:
      - Custom Object Fields
      summary: Zendesk Post  Api V2 Custom_objects Custom_object_key Fields
      description: 'Creates any of the following custom field types:


        * text (default when no "type" is specified)

        * textarea

        * checkbox

        * date

        * integer

        * decimal

        * regexp

        * dropdown

        * lookup

        * multiselect


        See [About custom field types](https://support.zendesk.com/hc/en-us/articles/203661866) in Zendesk help.


        #### Allowed For


        * Admins

        '
      parameters:
      - $ref: '#/components/parameters/CustomObjectKey'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomObjectFieldsCreateRequest'
            examples:
              default:
                $ref: '#/components/examples/CustomObjectFieldsCreateRequestExample'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomObjectFieldResponse'
              examples:
                default:
                  $ref: '#/components/examples/CustomObjectFieldCreateResponseExample'
  /api/v2/custom_objects/{custom_object_key}/fields/{custom_object_field_key_or_id}:
    get:
      operationId: ShowCustomObjectField
      tags:
      - Custom Object Fields
      summary: Zendesk Get  Api V2 Custom_objects Custom_object_key Fields Custom_object_field_key_or_id
      description: 'Returns a custom field for a specific object using a provided key or id of the field.

        #### Allowed For

        * Agents

        '
      parameters:
      - $ref: '#/components/parameters/CustomObjectKey'
      - $ref: '#/components/parameters/CustomObjectFieldKeyOrId'
      responses:
        '200':
          description: Custom Object Field
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomObjectFieldResponse'
              examples:
                default:
                  $ref: '#/components/examples/CustomObjectFieldCreateResponseExample'
    patch:
      operationId: UpdateCustomObjectField
      tags:
      - Custom Object Fields
      summary: Zendesk Patch  Api V2 Custom_objects Custom_object_key Fields Custom_object_field_key_or_id
      description: "Updates individual custom object fields. The updating rules are as follows:\n* Takes a `custom_object_field` object that specifies the properties to update\n* The `key` property cannot be updated\n* If updating a standard field, only the `title`, `description`, and `properties` attributes can be updated.\n* The `properties` parameter is comprised of four parts and can't be changed if any records exist for the object.\n    * `autoincrement_enabled`: A Boolean that enables and disables autonumbering. Must be false if is_unique is true.\n    * `autoincrement_prefix`: A string value that is used as a prefix to the autogenerated numbers. It can't exceed 30 characters.\n    * `autoincrement_padding`: An integer specifying the starting number of digits in the autogenerated numbers. This value may be between 0-9. However, if you create records in excess of of these digits, additional digits are added as necessary.\n    * `autoincrement_next_sequence`: An integer that will be used as the next number in the autonumbering sequence. It can't be negative or less than the current autonumbering value.\n    * `is_unique`: A Boolean that enforces uniqueness for manually entered record names. When true, custom object record names must be unique. Must be false if autoincrement_enabled is true.\n#### Allowed For\n* Admins"
      parameters:
      - $ref: '#/components/parameters/CustomObjectKey'
      - $ref: '#/components/parameters/CustomObjectFieldKeyOrId'
      responses:
        '200':
          description: Success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomObjectFieldResponse'
              examples:
                default:
                  $ref: '#/components/examples/CustomObjectFieldCreateResponseExample'
    delete:
      operationId: DeleteCustomObjectField
      tags:
      - Custom Object Fields
      summary: Zendesk Delete  Api V2 Custom_objects Custom_object_key Fields Custom_object_field_key_or_id
      description: 'Deletes a field with the specified key. Note: You can''t delete standard fields.

        #### Allowed For

        * Admins'
      parameters:
      - $ref: '#/components/parameters/CustomObjectKey'
      - $ref: '#/components/parameters/CustomObjectFieldKeyOrId'
      responses:
        '204':
          description: No content response
  /api/v2/custom_objects/{custom_object_key}/fields/reorder:
    put:
      operationId: ReorderCustomObjectFields
      tags:
      - Custom Object Fields
      summary: Zendesk Put  Api V2 Custom_objects Custom_object_key Fields Reorder
      description: 'Sets a preferred order of custom fields for a specific object by providing field ids in the desired order.

        #### Allowed For


        * Admins

        '
      parameters:
      - $ref: '#/components/parameters/CustomObjectKey'
      responses:
        '200':
          description: Reordered
          content:
            application/json:
              schema:
                type: string
                description: Empty response
                example: ''
              example: ''
  /api/v2/custom_objects/{custom_object_key}/limits/field_limit:
    get:
      operationId: CustomObjectFieldsLimit
      tags:
      - Custom Object Fields
      summary: Zendesk Get  Api V2 Custom_objects Custom_object_key Limits Field_limit
      description: 'List the current count and the limit for a custom object''s fields

        #### Allowed For

        * Agents'
      parameters:
      - $ref: '#/components/parameters/CustomObjectKey'
      responses:
        '200':
          description: Success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomObjectLimitsResponse'
              examples:
                default:
                  $ref: '#/components/examples/CustomObjectFieldsLimitResponseExample'
components:
  schemas:
    CustomObjectFieldsResponse:
      type: object
      properties:
        custom_object_fields:
          type: array
          items:
            $ref: '#/components/schemas/CustomObjectField'
    CustomObjectLimitsResponse:
      type: object
      properties:
        count:
          type: integer
          description: The current numnber of the requested resource
          readOnly: true
        limit:
          type: integer
          description: The maximum allowed number for the requested resource
          readOnly: true
    CustomObjectFieldResponse:
      type: object
      properties:
        custom_object_field:
          $ref: '#/components/schemas/CustomObjectField'
