openapi: 3.2.0
info:
  version: '1.0'
  title: Zendesk Any Channel Channel Framework API
  description: Needs a description.
tags:
- name: Channel Framework
paths:
  /api/v2/any_channel/channelback/report_error:
    post:
      operationId: ReportChannelbackError
      tags:
      - Channel Framework
      summary: Zendesk Post Api V2 Any_channel Channelback Report_error
      description: '#### Allowed For


        * Admins


        #### Request parameters


        The POST request takes a JSON object parameter which contains information about the

        problematic channelback.


        | Name | Type | Required | Comments

        | ------------------ | ----------| --------- | -------------------

        | instance_push_id | string | yes | The ID of the account to which data will be pushed. This was passed to the integration service when the administrator set up the account

        | external_id | string | yes | Unique identifier of the external resource from the original channelback (string)

        | description | string | no | A human readable description of the error

        | request_id | string | no | A unique identifier for the request


        #### Response format


        The response does not include a response body'
      responses:
        '200':
          description: Success response
          content:
            application/json:
              schema:
                type: string
                description: Empty response
                example: ''
              example: ''
  /api/v2/any_channel/push:
    post:
      operationId: PushContentToSupport
      tags:
      - Channel Framework
      summary: Zendesk Post Api V2 Any_channel Push
      description: Pushes Channel framework content to Zendesk.
      responses:
        '200':
          description: Success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChannelFrameworkPushResultsResponse'
              examples:
                default:
                  $ref: '#/components/examples/ChannelFrameworkPushResultsResponseExample'
  /api/v2/any_channel/validate_token:
    post:
      operationId: ValidateToken
      tags:
      - Channel Framework
      summary: Zendesk Post Api V2 Any_channel Validate_token
      description: '#### Allowed For


        * Admins


        #### Request parameters


        The POST request takes a JSON object parameter which contains the token to be validated.


        | Name | Type | Required | Comments

        | ------------------ | ----------| --------- | -------------------

        | instance_push_id | string | yes | The ID of the account to which data will be pushed. This was passed to the integration service when the administrator set up the account

        | request_id | string | no | A unique identifier for the push request


        #### Response format


        The response body is empty.'
      responses:
        '200':
          description: Success response
          content:
            application/json:
              schema:
                type: string
                description: Empty response
                example: ''
              example: ''
components:
  schemas:
    ChannelFrameworkPushResultsResponse:
      type: object
      properties:
        results:
          type: array
          description: An array of [result objects](#result-object)
          items:
            $ref: '#/components/schemas/ChannelFrameworkResultObject'
