openapi: 3.2.0
info:
  version: '1.0'
  title: Zendesk Oauth Grant Type Tokens API
  description: Needs a description.
tags:
- name: Grant Type Tokens
paths:
  /oauth/tokens:
    post:
      operationId: CreateTokenForGrantType
      tags:
      - Grant Type Tokens
      summary: Zendesk Post Oauth Tokens
      description: Returns an OAuth access token in exchange for an authorization code valid for 120 seconds.
      responses:
        '201':
          description: Created response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OAuthTokenForGrantTypesObject'
              examples:
                default:
                  $ref: '#/components/examples/OAuthTokenForGrantTypesResponseExample'
